### ISSUE TITLE
BUILD NODE IMAGE: No handlers could be found for logger

### ISSUE THREAD

**Issue by 0xmichalis** [openshift-eng/aos-cd-jobs#1313]
Happens in the azure conformance job intermittently

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19175/test_pull_request_origin_extended_conformance_azure/194/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19355/test_pull_request_origin_extended_conformance_azure/198/

@pschiffe @kwoodson our very first flake

/assign pschiffe

**Comment by pschiffe** [comment]
Full traceback:
```
No handlers could be found for logger "msrestazure.azure_active_directory"
Traceback (most recent call last):
  File "/tmp/ansible_QtGy2c/ansible_module_azure_rm_storageaccount.py", line 452, in <module>
    main()
  File "/tmp/ansible_QtGy2c/ansible_module_azure_rm_storageaccount.py", line 449, in main
    AzureRMStorageAccount()
  File "/tmp/ansible_QtGy2c/ansible_module_azure_rm_storageaccount.py", line 191, in __init__
    supports_check_mode=True)
  File "/tmp/ansible_QtGy2c/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 347, in __init__
  File "/tmp/ansible_QtGy2c/ansible_module_azure_rm_storageaccount.py", line 213, in exec_module
    self.account_dict = self.get_account()
  File "/tmp/ansible_QtGy2c/ansible_module_azure_rm_storageaccount.py", line 253, in get_account
    account_obj = self.storage_client.storage_accounts.get_properties(self.resource_group, self.name)
  File "/usr/lib/python2.7/site-packages/azure/mgmt/storage/v2017_10_01/operations/storage_accounts_operations.py", line 309, in get_properties
    response = self._client.send(request, header_parameters, **operation_config)
  File "/usr/lib/python2.7/site-packages/msrest/service_client.py", line 257, in send
    **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python2.7/site-packages/urllib3/util/retry.py", line 226, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```
